[package]
name="roaster_contract"
version="0.1.0"
edition="2021"

[lib]
crate-type=["cdylib"]

[dependencies]
soroban-sdk="20.0.0-rc.3"
alloc={version="*", optional=true}

[dev-dependencies]
soroban-sdk={version="20.0.0-rc.3", features=["testutils"]}